
title: Bio-Data
url: 'https://umangmmehta.github.io/bio-data/'
baseurl: '/bio-data' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Umang Mehta
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone: +91 22 28619951,     +91 9892959951
website:
linkedin:
github:
twitter: '@oomuung'

#Update all the sections by editing the files inside _includes folder.
